version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the Docker image
      - docker build -t flask-app .
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker tag flask-app:latest 034362045846.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo:latest
      - docker push 034362045846.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo:latest

artifacts:
  files: '**/*'
  base-directory: 'build'
